version: "3.8"
services:
  serve:
    build:
      dockerfile: container/serve/Dockerfile
      context: ..
    ports:
      - "1342:1342"
    volumes:
      - cache:/root/cache
  git-ssh:
    build:
      dockerfile: container/git-ssh/Dockerfile
      context: ..
    restart: always
    ports:
      - "2002:2002"
    volumes:
      - storage:/var/lib/shell/storage
  git-http:
    build:
      dockerfile: container/git-http/Dockerfile
      context: ..
    restart: always
    ports:
      - "1001:80"
    volumes:
      - storage:/var/www/storage
volumes:
  cache:
  storage:
