version: "3.8"
services:
  #serve:
    #build:
      #context: ..
      #dockerfile: container/serve/Dockerfile
    #ports:
      #- "1342:1342"
    #volumes:
      #- cache:/root/cache
  git-ssh:
    build:
      context: ..
      dockerfile: container/git-ssh/Dockerfile
    restart: always
    ports:
      - "2002:2002"
    volumes:
      - storage:/var/lib/shell/storage
  git-http:
    build:
      context: ..
      dockerfile: container/git-http/Dockerfile
    restart: always
    ports:
      - "1002:80"
    volumes:
      - storage:/var/lib/shell/storage
volumes:
  cache:
  storage:
