[package]
name = "server"
version = "0.1.0"
authors = ["Isaac Snow <isaacjsnow@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
shared = { path = "../shared" }
tokio = { version = "1.5.0", features = ["full"] }
hyper = { version = "0.14.7", features = ["full"] }
dirs = "3.0.2"
bytes = "1.0.1"
http = "0.2.4"
futures = "0.3.15"
bincode = "1.3.3"
base64 = "0.13.0"
serde = { version = "1.0.126", features = ["derive"] }
serde_json = "1.0.64"
