[package]
name = "jago"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitflags = "1.3.2"
crdts = "7.0.0"
itertools = "0.10.3"
crossterm = { version = "0.22.1", features = ["event-stream"] }
tokio = { version = "1.16.1", features = ["rt", "rt-multi-thread"] }
log = "0.4.14"
thiserror = "1.0.30"
unicode-segmentation = "1.8.0"

# ___

fst = { version = "0.4.7", features = ["levenshtein"] }
futures = "0.3.21"
ignore = "0.4.18"
ndarray = "0.15.4"
num-traits = "0.2.14"
once_cell = "1.9.0"
rand = "0.8.4"
strsim = "0.10.0"
textwrap = "0.14.2"
untrusted = "0.9.0"
serde = "1.0.136"
anyhow = "1.0.53"

[dependencies.ide]
git = "https://github.com/rust-analyzer/rust-analyzer"
branch = "release"
package = "ide"
optional = true
