[package]
name = "jago"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crdts = "7.0.0"
crossterm = "0.22.1"
fst = { version = "0.4.7", features = ["levenshtein"] }
ignore = "0.4.18"
itertools = "0.10.3"
ndarray = "0.15.4"
num-traits = "0.2.14"
once_cell = "1.9.0"
rand = "0.8.4"
strsim = "0.10.0"
thiserror = "1.0.30"
unicode-segmentation = "1.8.0"
