[package]
name = "jago"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default=[]

[dependencies]
program = { path = "shelf/program" }
logger = { path = "shelf/logger", optional = true }
pipe = { path = "shelf/pipe", optional = true }

[workspace]
members = ["shelf/*"]
