[package]
name = "jago"
version = "0.1.0"
edition = "2018"
description = "variable utopia"
resolver = "2"

[profile.test]
opt-level = 0
debug = true

[lib]
crate-type = ["staticlib", "cdylib", "rlib"]

[features]
default=["logs", "handle", "interface"]
logs=["log", "pretty_env_logger"]
pack=["wasm-pack"]
serve=["warp", "tokio"]

[[bin]]
name = "jago"
path = "gen/bin/desktop.rs"

[package.metadata.bundle.bin.jago]
name="jago"
identifier = "community.jago"
resources = ["assets/**/*"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wasm-pack = { version = "0.10.1", optional = true }
thiserror = "1.0.30"
log = { version = "0.4.14", optional = true }
pretty_env_logger = { version = "0.4.0", optional = true }
dirs = "4.0.0"
failure = "0.1.8"
ignore = "0.4.18"
tokio = { version = "1.12.0", features = ["full"], optional = true }
warp = { version = "0.3.1", optional = true }
#binary-install = "0.0.2"
#mozprofile = "0.7.3"
byteorder = "1.4.3"
serde_json = "1.0.68"
anyhow = "1.0.44"
zip = "0.5.13"
walkdir = "2.3.2"
workspace = { path = "crates/workspace" }
context = { path = "crates/context" }
#watch = { path = "shelf/watch" }
#glass = { path = "shelf/glass" }
interface = { path = "crates/interface",  optional = true }
mobile-entry-point = { version = "0.1.0" }
handle = { path = "crates/handle",  optional = true }
once_cell = "1.8.0"
crdts = "7.0.0"
display = { path = "crates/display" }

[target.'cfg(target_os = "android")'.dependencies]
android_logger = "0.9.0"
ndk-glue = "0.2.1"

[workspace]
members = ["shelf/*", "crates/*"]
exclude = ["table/phone"]
