[package]
name = "jago"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4.14"
simplelog = "0.11.2"
context = { path = "crates/context" }
thiserror = "1.0.30"
dirs = "4.0.0"

[target.'cfg(target_arch = "wasm32")'.dependencies]
web = { path = "crates/web" }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
ansi = { path = "crates/ansi" }
environment = { path = "crates/environment" }

[workspace]
members = ["crates/*"]
