[package]
name = "jago"
version = "0.1.0"
authors = ["Isaac Snow <isaacjsnow@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
git2 = "0.13.19"
dirs = "3.0.2"
nom = "6.1.2"
tokio = { version = "1.5.0", features = ["full"] }
hyper = { version = "0.14.7", features = ["full"] }
bytes = "1.0.1"
http = "0.2.4"
