[package]
name = "jago"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = "0.22.1"
thiserror = "1.0.30"
unicode-segmentation = "1.8.0"
