[package]
name = "jago"
version = "0.1.0"
authors = ["Isaac Snow <isaacjsnow@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
serve=["server"]
store=["storage"]

[dependencies]
logger = { path = "library/logger" }
server = { path = "library/server", optional = true }
storage = { path = "library/storage", optional = true }
log = "0.4.14"
#platform = { path = "library/platform" }

[workspace]
members = [
    "library/logger",
    "library/shared",
    "library/server",
    "library/storage",
    "library/platform"
]
