[package]
name = "jago"
version = "0.1.0"
authors = ["Isaac Snow <isaacjsnow@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
serve=["server"]

[dependencies]
logger = { path = "library/logger" }
server = { path = "library/server", optional = true }
log = "0.4.14"

[workspace]
members = [
    "library/logger",
    "library/server",
    "library/shared"
]
