[package]
name = "jago"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4.14"
thiserror = "1.0.30"
futures = "0.3.21"
once_cell = "1.10.0"
crdts = "7.0.0"
dirs = "4.0.0"
