[package]
name = "jago"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crdts = "7.0.0"
crossterm = { version = "0.22.1", features = ["event-stream"] }
tokio = { version = "1.16.1", features = ["rt", "rt-multi-thread"] }
log = "0.4.14"
thiserror = "1.0.30"
futures = "0.3.21"
anyhow = "1.0.53"
bitflags = "1.3.2"
itertools = "0.10.3"
ndarray = "0.15.4"
serde = { version = "1.0.136", features = ["derive"] }
unicode-segmentation = "1.9.0"
textwrap = "0.15.0"
