[package]
name = "jago"
version = "0.1.0"
authors = ["Isaac Snow <isaacjsnow@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default=["logger"]

[dependencies]
log = "0.4.14"
program = { path = "library/program" }
logger = { path = "library/logger", optional = true }
server = { path = "library/server", optional = true }
storage = { path = "library/storage", optional = true }
platform = { path = "library/platform", optional = true }
interface = { path = "library/interface", optional = true }
lense = { path = "library/lense", optional = true }
#window = { path = "library/window", optional = true }
filter = { path = "library/filter", optional = true }
shell = { path = "library/shell", optional = true }

[workspace]
members = ["library/*"]
