[package]
name = "jago"
version = "0.1.0"
authors = ["Isaac Snow <isaacjsnow@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default=["log"]
log=["logger"]
serve=["tokio", "old"]

[dependencies]
logger = { path = "library/logger", optional = true }
tokio = { version = "1.5.0", features = ["full"], optional = true }
old = { path = "library/old", optional = true }
cfg-if = "1.0.0"
clap = "2.33.3"

[workspace]
members = ["library/logger", "library/old"]
