[package]
name = "jago"
version = "0.1.0"
authors = ["Isaac Snow <isaacjsnow@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default=["logs"]
logs=["logger"]
serve=["server"]
store=["storage"]

[dependencies]
platform = { path = "library/platform" }
logger = { path = "library/logger", optional = true }
server = { path = "library/server", optional = true }
storage = { path = "library/storage", optional = true }
log = "0.4.14"

[workspace]
members = [
    "library/platform",
    "library/logger",
    "library/shared",
    "library/server",
    "library/storage"
]
