[package]
name = "jago"
version = "0.1.0"
edition = "2018"
description = "variable utopia"

[package.metadata.bundle.bin.pipe]
name = "jago"
identifier = "community.jago"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default=[]
logs=["log", "pretty_env_logger"]

#[[bin]]
#name = "pipe"
#required-features = ["pipe"]
#path = "src/main.rs"

[dependencies]
program = { path = "shelf/program" }
logger = { path = "shelf/logger", optional = true }
pipe = { path = "shelf/pipe", optional = true }
magazine = { path = "shelf/magazine", optional = true }
plant = { path = "shelf/plant", optional = true }
wasm-pack = "0.10.1"
thiserror = "1.0.30"
log = { version = "0.4.14", optional = true }
pretty_env_logger = { version = "0.4.0", optional = true }
dirs = "4.0.0"
failure = "0.1.8"
ignore = "0.4.18"
tokio = { version = "1.12.0", features = ["full"] }
warp = "0.3.1"

[workspace]
members = ["shelf/*", "crates/*"]
