[package]
name = "mobile"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
android_logger = "0.10.1"
winit = "0.25.0"
tokio = "1.7.1"
