[package]
name = "identity"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
author = { path = "../author" }
rpassword = "5.0.1"
context = { path = "../context" }
libc = "0.2.97"
log = "0.4.14"
ring = "0.16.20"
untrusted = "0.7.1"
openssl = { version = "0.10.35", features = ["vendored"] }
lazy_static = "1.4.0"
secrets = "1.1.0"
rand = "0.8.4"
