[package]
name = "context"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
author = { path = "../author" }
dirs = "3.0.2"
lazy_static = "1.4.0"
shellexpand = "2.1.0"
nom = "6.2.1"
