[package]
name = "search"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
author = { path = "../author" }
hyper = { version = "0.14.9", features = [ "full" ] }
tokio = { version = "1.7.1", features = [ "full" ] }
http = "0.2.4"
hyper-tls = "0.5.0"
reqwest = "0.11.4"
url = { version = "2.2.2", features = [ "serde" ] }
futures = "0.3.15"
serde = { version = "1.0.126", features = [ "derive" ] }
quick-xml = { version = "0.22.0", features = [ "serialize" ] }
xml5ever = "0.16.1"
log = "0.4.14"
regex = "1.4.6"
nom = { version = "6.2.1", features = ["regexp"] }
lazy_static = "1.4.0"
