#!/bin/bash
set -e

if [ $1 == "1" ]; then
    echo "cleaning up"

    docker compose -f ~/local/jago/container/compose.yml down

    docker volume rm container_storage
    docker volume rm container_cache
fi

~/local/jago/instrument/container/build

docker compose -f ~/local/jago/container/compose.yml create
docker compose -f ~/local/jago/container/compose.yml start
