#!/bin/bash

if [ $1 == "1" ]; then
    echo "cleaning up"
    docker compose -f ~/local/jago/container/compose.yml down
    docker compose -f ~/local/jago/container/compose.yml rm

    docker volume rm container_storage
    #docker volume rm container_cache

    docker compose -f ~/local/jago/container/compose.yml build
fi

docker compose -f ~/local/jago/container/compose.yml create
docker compose -f ~/local/jago/container/compose.yml start
