[package]
name = "trusty"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]

[dependencies]
author = { path = "../author" }
untrusted = "0.7.1"
nom = "6.2.1"
log = "0.4.14"
tendril = "0.4.2"
bitflags = "1.2.1"
either = "1.6.1"

[dev-dependencies]
logger = { path = "../logger" }
