[package]
name = "source"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
author = { path = "../author" }
rayon = "1.5.1"
dirs = "3.0.2"
log = "0.4.14"
either = "1.6.1"
tokio = "1.7.1"
nom = "6.2.1"
