[package]
name = "shell"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
author = { path = "../author" }
nom = "6.2.1"
glob = "0.3.0"
ignore = "0.4.18"
tempfile = "3.2.0"
dirs = "3.0.2"
library = { path = "../library" }
log = "0.4.14"
syn = "1.0.73"
quote = "1.0.9"
context = { path = "../context" }
