#!/bin/bash
set -ex

project=$HOME/local/jago
target=$HOME/local/jago/target

#build=release
#build_flag=--release

build=debug
build_flag=

cargo build $build_flag --package web --lib --target wasm32-unknown-unknown \
    --features web/content

wasm-bindgen $target/wasm32-unknown-unknown/$build/web.wasm \
    --target no-modules \
    --out-dir $target/web/content \
    --no-typescript

cp $target/web/content/web.js $target/web/content/content.js
cat $project/shelf/web/src/content.js >> $target/web/content/content.js

for context in "popup" "background"
do
    cargo build $build_flag --package web --lib --target wasm32-unknown-unknown \
        --features web/$context

    wasm-bindgen $target/wasm32-unknown-unknown/$build/web.wasm \
        --target web \
        --out-dir $target/web/$context \
        --no-typescript
done

for context in "popup" "background"
do
    sed "s/\$context/$context/g" $project/shelf/web/src/lib.html > $target/web/$context/mod.html
    cp $project/shelf/web/src/lib.js $target/web/$context/mod.js

    if [ -f "$project/shelf/web/src/$context.js" ]; then
        cp $project/shelf/web/src/$context.js $target/web/$context
    fi

    if [ -d "$project/shelf/web/src/$context" ]; then
        cp $project/shelf/web/src/$context/*.js $target/web/$context/
    fi
done

cargo build $build_flag --features pipe

cp $project/shelf/web/src/lib.json $target/web/manifest.json
cp -R $project/shelf/web/asset $target/web/asset

cp $project/shelf/web/src/life/mod.html $target/web/popup/mod.html

echo "{
  \"name\": \"jago\",
  \"description\": \"Interact with anarchy.\",
  \"path\": \"$target/$build/jago\",
  \"type\": \"stdio\",
  \"allowed_extensions\": [ \"web@jago.community\" ]
}" > "$HOME/Library/Application Support/Mozilla/NativeMessagingHosts/jago.json"

#$project/shelf/web/extend
