#!/bin/bash

context=$(dirname $1)
name=$(basename $1)

if [ "$name" != ".git" ]; then
    mkdir -p "$TARGET_DIRECTORY/$(basename $context)"
    ln -s $1 "$TARGET_DIRECTORY/$(basename $context)/$name"
fi
