#!/bin/bash
set -ex

source ~/variables

TARGET_DIRECTORY=${TARGET_DIRECTORY:-"~/target"}
STORAGE_DIRECTORY=${STORAGE_DIRECTORY:-"~/storage"}

STAGING_DIRECTORY="$TARGET_DIRECTORY/staging"

REPOSITORY_NAME=$1
STAGING_PATH="$STAGING_DIRECTORY/$REPOSITORY_NAME.git"

REPOSITORY_RELATIVE_NAME=${STAGING_PATH#$STAGING_DIRECTORY}

mkdir -p $STAGING_PATH

pushd $STAGING_PATH > /dev/null

git init --bare --quiet
git symbolic-ref HEAD refs/heads/main

touch git-daemon-export-ok
cp hooks/post-update.sample hooks/post-update
git update-server-info
chown -Rf git:git "$STAGING_PATH"

echo "Git repository $REPOSITORY_RELATIVE_NAME created"

popd > /dev/null

REPOSITORY_CONTEXT=$(dirname $REPOSITORY_RELATIVE_NAME)

mkdir "$TARGET_DIRECTORY/$REPOSITORY_CONTEXT"

sudo mkdir -p "$STORAGE_DIRECTORY/$REPOSITORY_CONTEXT"
sudo mv $STAGING_PATH "$STORAGE_DIRECTORY/$REPOSITORY_RELATIVE_NAME"

$TARGET_DIRECTORY/git-shell-commands/repository-link "$STORAGE_DIRECTORY/$REPOSITORY_RELATIVE_NAME"
