#!/bin/bash
set -ex

STORAGE_DIRECTORY=${STORAGE_DIRECTORY:-"/var/lib/shell/storage"}
TARGET_DIRECTORY=${TARGET_DIRECTORY:-"/var/www/git"}

#cargo run -- log info "looking in $STORAGE_DIRECTORY"

find $STORAGE_DIRECTORY -name "*.git" -print0 | xargs -0 -n 1 ~/git-shell-commands/repository-link

#for context in $STORAGE_DIRECTORY; do
    #jago log info context $context
    #for repository in $context/*.git; do
        #jago log info context $context
        #if [ -d "$repository" ]; then
            #target=/var/www/git/${repository#$STORAGE_DIRECTORY/}
            #jago log info "target=$target" "context=$context" "repository=$repository"
            ##mkdir -p $target
            ##ln -s $repository $target
        #fi
    #done
#done

#nginx
