[package]
name = "instrument"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
author = { path = "../author" }
context = { path = "../context" }
log = "0.4.14"
