[package]
name = "interface"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wgpu = "0.9.0"
font-kit = "0.10.1"
wgpu_glyph = "0.13.0"
winit = "0.25.0"
futures = "0.3.15"
log = "0.4.14"
author = { path = "../author" }
rand = "0.8.4"
palette = "0.5.0"
bitflags = "1.2.1"
matches = "0.1.8"
