[package]
name = "library"
version = "0.1.0"
authors = ["Isaac Snow <isaacjsnow@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
#quote = "1.0.9"
serde = { version = "1.0.126", features = ["derive"] }
toml = "0.5.8"
glob = "0.3.0"
ignore = "0.4.18"
#proc-macro2-diagnostics = "0.9.1"
#syn = { version = "1.0.73", features = ["full"] }
#matches = "0.1.8"
#unicode-segmentation = "1.7.1"
author = { path = "../author" }
