[package]
name = "map"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
author = { path = "../author" }
nom = "6.2.1"
serde_json = "1.0.64"
hyper = "0.14.9"
base64 = "0.13.0"
ignore = "0.4.18"
glob = "0.3.0"
dirs = "3.0.2"
futures = { version = "0.3.15", features = [ "thread-pool" ] }
log = "0.4.14"
globset = "0.4.8"
