[package]
name = "logger"
version = "0.1.0"
authors = ["Isaac Snow <isaacjsnow@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
flexi_logger = { version = "0.17", default_features = false }
log = { version = "0.4.14" }
dirs = {version = "3.0.2" }
author = { path = "../author" }
library = { path = "../library" }
