[package]
name = "platform"
version = "0.1.0"
authors = ["Isaac Snow <isaacjsnow@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0.126", features = ["derive"] }
tinytemplate = "1.2.1"
tempfile = "3.2.0"
bollard = "0.10.1"
tokio = { version = "1.5.0", features = ["full"] }
futures-util = "0.3.15"
library = { path = "../library" }
dirs = "3.0.2"
tar = "0.4.35"
ignore = "0.4.18"
log = "0.4.14"
hyper = "0.14.9"
server = { path = "../server" }
futures = "0.3.15"

[dev-dependencies]
tokio-test = "0.4.1"
