[package]
name = "context"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "1.0.30"
crdts = "7.0.0"
bitflags = "1.3.2"
wasm-bindgen-futures = "0.4.29"
log = "0.4.14"
