[package]
name = "context"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crdts = "7.0.0"
log = "0.4.14"
thiserror = "1.0.30"
