[package]
name = "http"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
logs = { path = "../logs" }
log = "0.4.14"
simplelog = "0.11.2"
warp = "0.3.2"
thiserror = "1.0.30"
